### ISSUE TITLE
Read UUID

### ISSUE THREAD

**Issue by martp00** [balenablocks/fin-block#61]
How I can read the UUID number from the device (balena-fin v1.1)?  SDK (https://github.com/balena-io-hardware/balena-fin-sdk) doesn't work (https://github.com/balena-io-hardware/balena-fin-sdk/issues/5) and deprecated.

Since in this thread is mark done (https://github.com/balenablocks/fin-block/issues/2), I was hoping to find a way.
Didn't see any information about this in doc folder. Should it have a REST interface ?

**Comment by Bucknalla** [comment]
@martp00 are you looking for the manufacturing serial ID of the fin? Or the balena UUID generated at balenaCloud?

**Comment by martp00** [comment]
I was searching UUID generated at balenaCloud, but your question makes me realize that they are 2 completely different field.
The /firmware method return to the manufacturing serial ID.

I find the Balena UUID into environment variable (os.getenv('BALENA_DEVICE_UUID')).
